#%RAML 1.0 NamedExample
value: 
  notification-id :  "N0111"
  notification-entity-id: "PR10112"
  event-type: "ProductUpdated"
  triggered-by: "Salesforce"  
  target-name :  "IRIIS"
  target-entity-id :  "TRG0001"  
  date-created :  "20230414T1015"
  additional-identifier-1: "ADDID1"
  additional-identifier-2: "ADDID2"
  additional-identifier-3: "ADDID3"  