#%RAML 1.0 NamedExample
value: 
  event-id :  "E1001"
  event-type: "Approval"
  event-description: "Product Approved in Salesforce"  
  event-entity-id :  "PRD019029"
  triggered-by :  "Salesforce"  
  date-created :  "20230414T1015"